// export const  DEFA
export const RECEIVE_ADDRESS = 'receive_address';
export const RECEIVE_BANNERS = 'receive_banners';
export const RECEIVE_INDEXITEMS = 'receive_indexItems';
export const RECEIVE_CATEGORYS = 'receive_categorys';
export const RECEIVE_CATEGORYITEMS = 'receive_categoryitems';
export const RECEIVE_USERINFO = 'receive_userinfo';
export const RECEIVE_RECORDUSER = 'receive_recorduser';
export const RECEIVE_LOGOUT = 'receive_logout';
export const RECEIVE_PRODUCTID = 'receive_productid';
export const RECEIVE_ADDCAR = 'receive_addcar';
export const RECEIVE_CARS = 'receive_cars';
export const  INCREMENT_FOOD_COUNT= 'receive_increment_food';
export const  DECREMENT_FOOD_COUNT= 'receive_decrement_food';
export const   SELECTED_ALL_FOODS= 'receive_selectedall';
export const   UNSELECTED_ALL_FOODS= 'receive_unselectedall';
export const   SELECTED_ALL_EDITFOODS= 'receive_selectededitall';
export const   UNLECTED_ALL_EDITFOODS= 'receive_unselectededitall';
export const   RECEIVE_INITEDITSELECTED= 'receive_initeditselected';
